server:
 error:
  include-stacktrace: on_param

spring:
 datasource:
   url: jdbc:mysql://localhost:3306/bibliotecaapi?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
   username: root
   password: mysql
   driverClassName: com.mysql.cj.jdbc.Driver
 jpa:
  hibernate:
   ddl-auto: update


logging:
 level:
  org:
   hibernate:
    SQL: DEBUG
